name: Build

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "40 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
  
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
  
    - run: corepack enable

    - run: pnpm install

    - run: pnpm exec node ./index.js
      env:
        LB_TOKEN: ${{ secrets.LB_TOKEN }}
      
    - run: |
        echo -e "/*\n  X-Robots-Tag: noindex" > dist/_headers

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CF_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        projectName: ${{ secrets.CF_PROJECT_NAME }}
        directory: dist
