name: Build

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4
    
    - name: Get Date
      id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache temp folder
      uses: actions/cache@v4
      with:
        path: temp
        key: temp-${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          temp-${{ runner.os }}-

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
  
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
  
    - run: corepack enable

    - run: pnpm install

    - run: pnpm exec node ./index.js
      env:
        LB_TOKEN: ${{ secrets.LB_TOKEN }}

    - name: Publish generated content to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ./dist
