name: Build on Cloudflare Pages

on:
  schedule:
    - cron: "40 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Request to Cloudflare Pages Webhook
      run: curl -If ${{ secrets.CF_PAGES_WEBHOOK }}
